name: betcal
description: A Better's Application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  blur_bottom_bar: ^1.0.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.14
  google_fonts: ^4.0.3
  iconsax: ^0.0.8
  internet_connection_checker: ^1.0.0+1
  page_transition: ^2.0.9
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# native splash screen
flutter_native_splash:
  color: "#ffffff"
  image: images/logo.png
  android_12:
    image: images/logo.png
    icon_background_color: "#ffffff"
  fullscreen: true
  android: true
  ios: true

# launcher icon
flutter_icons:
  image_path: "images/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  web:
    generate: true
    image_path: "images/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - images/
